export const metadata = {
    title: "Payload CMS",
    description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return <>{children}</>;
}
